# Model Training Pipeline
This pipeline is used for traininig the folowing list of regression models to predict the concentration inmicro mollar, from a given DPV voltammogram signal.

### Lois of regression models:
- Linear Regression
- Ridge Regression
- Elastic Net
- Support Vector Regression
- Decision Tree
- Random Forest
- Extreme Gradient Boost

In [2]:
# imports
import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNet, LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, KFold, LeaveOneOut
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor

In [ ]:
df = pd.read_csv('vectorized/core.csv')
df.head()

   sig_id  peak_current  peak_potential  peak_AUC  peak_FWHM  concentration
0       0     34.861237       -0.377680  2.857497   0.082198          100.0
1       1     34.122628       -0.382515  2.858868   0.082198          100.0
2       2     33.952617       -0.382515  2.788808   0.077363          100.0
3       3     22.310970       -0.382515  1.527314   0.062857           50.0
4       4     23.119320       -0.382515  1.600881   0.062857           50.0

In [5]:
X = df.drop(['sig_id', 'concentration'], axis=1)
y = df['concentration']
print(X.shape)
print(y.shape)

(40, 4)
(40,)

In [9]:
loo = LeaveOneOut()
model = LinearRegression()

y_true = []
y_pred = []

for train_idx, test_idx in loo.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)
    pred = model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== Linear Regression with LOOCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_lr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_lr)

=== Linear Regression with LOOCV ===
MAE  : 0.924852
RMSE : 1.306779
R²   : 0.997727

    y_true      y_pred  residual  abs_error
0   100.00   99.790021  0.209979   0.209979
1   100.00  101.321147 -1.321147   1.321147
2   100.00   97.079781  2.920219   2.920219
3    50.00   51.107950 -1.107950   1.107950
4    50.00   54.444805 -4.444805   4.444805
5    50.00   52.037904 -2.037904   2.037904
6    25.00   23.248117  1.751883   1.751883
7    25.00   23.021035  1.978965   1.978965
8    25.00   23.072405  1.927595   1.927595
9    15.00   13.748714  1.251286   1.251286
10   15.00   13.371947  1.628053   1.628053
11   15.00   13.172345  1.827655   1.827655
12   10.00    9.245907  0.754093   0.754093
13   10.00    9.505478  0.494522   0.494522
14   10.00    9.545408  0.454592   0.454592
15    7.50    7.299837  0.200163   0.200163
16    7.50    7.453781  0.046219   0.046219
17    7.50    6.558187  0.941813   0.941813
18    5.00    4.996558  0.003442   0.003442
19    5.00    4.908065  0.091935   0.091935
20    5.00    4.922487  0.077513   0.077513
21    2.50    2.867089 -0.367089   0.367089
22    2.50    3.078013 -0.578013   0.578013
23    1.00    1.588153 -0.588153   0.588153
24    1.00    1.792262 -0.792262   0.792262
25    1.00    1.785080 -0.785080   0.785080
26    0.50    1.982692 -1.482692   1.482692
27    0.50    2.247011 -1.747011   1.747011
28    0.50    1.580452 -1.080452   1.080452
29    0.50    0.380539  0.119461   0.119461
30    0.50    0.368416  0.131584   0.131584
31    0.50    0.383353  0.116647   0.116647
32    0.25    0.398077 -0.148077   0.148077
33    0.25    0.174277  0.075723   0.075723
34    0.25    0.197563  0.052437   0.052437
35    0.10    0.108316 -0.008316   0.008316
36    0.10    1.867524 -1.767524   1.767524
37    0.10   -0.526818  0.626818   0.626818
38    0.10    0.681142 -0.581142   0.581142
39    0.10    0.573887 -0.473887   0.473887

In [10]:
outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = DecisionTreeRegressor(random_state=42)

    param_grid = {
        "max_depth": [2, 3, 4, 5, None],
        "min_samples_split": [2, 3, 4, 5, 6],
        "min_samples_leaf": [1, 2, 3, 4],
        "ccp_alpha": [0.0, 0.001, 0.01, 0.05]
    }

    grid = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )

    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(grid.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== DecisionTreeRegressor with nested LOOCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_dtr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_dtr)

# Best hyperparameters chosen in each outer fold
best_params_dtr = pd.DataFrame(best_params_per_fold)
display(best_params_dtr)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_dtr.value_counts().reset_index(name="count"))

=== DecisionTreeRegressor with nested LOOCV ===
MAE  : 0.062500
RMSE : 0.395285
R²   : 0.999792

    y_true  y_pred  residual  abs_error
0   100.00  100.00       0.0        0.0
1   100.00  100.00       0.0        0.0
2   100.00  100.00       0.0        0.0
3    50.00   50.00       0.0        0.0
4    50.00   50.00       0.0        0.0
5    50.00   50.00       0.0        0.0
6    25.00   25.00       0.0        0.0
7    25.00   25.00       0.0        0.0
8    25.00   25.00       0.0        0.0
9    15.00   15.00       0.0        0.0
10   15.00   15.00       0.0        0.0
11   15.00   15.00       0.0        0.0
12   10.00   10.00       0.0        0.0
13   10.00    7.50       2.5        2.5
14   10.00   10.00       0.0        0.0
15    7.50    7.50       0.0        0.0
16    7.50    7.50       0.0        0.0
17    7.50    7.50       0.0        0.0
18    5.00    5.00       0.0        0.0
19    5.00    5.00       0.0        0.0
20    5.00    5.00       0.0        0.0
21    2.50    2.50       0.0        0.0
22    2.50    2.50       0.0        0.0
23    1.00    1.00       0.0        0.0
24    1.00    1.00       0.0        0.0
25    1.00    1.00       0.0        0.0
26    0.50    0.50       0.0        0.0
27    0.50    0.50       0.0        0.0
28    0.50    0.50       0.0        0.0
29    0.50    0.50       0.0        0.0
30    0.50    0.50       0.0        0.0
31    0.50    0.50       0.0        0.0
32    0.25    0.25       0.0        0.0
33    0.25    0.25       0.0        0.0
34    0.25    0.25       0.0        0.0
35    0.10    0.10       0.0        0.0
36    0.10    0.10       0.0        0.0
37    0.10    0.10       0.0        0.0
38    0.10    0.10       0.0        0.0
39    0.10    0.10       0.0        0.0

    ccp_alpha  max_depth  min_samples_leaf  min_samples_split
0         0.0        NaN                 1                  4
1         0.0        NaN                 1                  4
2         0.0        NaN                 1                  4
3         0.0        NaN                 1                  2
4         0.0        NaN                 1                  2
5         0.0        NaN                 1                  2
6         0.0        NaN                 1                  2
7         0.0        NaN                 1                  2
8         0.0        NaN                 1                  2
9         0.0        NaN                 1                  2
10        0.0        NaN                 1                  2
11        0.0        NaN                 1                  2
12        0.0        NaN                 1                  2
13        0.0        NaN                 1                  2
14        0.0        5.0                 1                  2
15        0.0        NaN                 1                  2
16        0.0        NaN                 1                  2
17        0.0        NaN                 1                  2
18        0.0        NaN                 1                  2
19        0.0        NaN                 1                  2
20        0.0        NaN                 1                  2
21        0.0        4.0                 1                  2
22        0.0        4.0                 1                  2
23        0.0        NaN                 1                  2
24        0.0        NaN                 1                  2
25        0.0        NaN                 1                  2
26        0.0        NaN                 1                  2
27        0.0        NaN                 1                  2
28        0.0        NaN                 1                  2
29        0.0        NaN                 1                  2
30        0.0        NaN                 1                  2
31        0.0        NaN                 1                  2
32        0.0        NaN                 1                  2
33        0.0        NaN                 1                  2
34        0.0        NaN                 1                  2
35        0.0        NaN                 1                  2
36        0.0        NaN                 1                  2
37        0.0        NaN                 1                  2
38        0.0        NaN                 1                  2
39        0.0        NaN                 1                  2

Most frequent best parameter sets:

   ccp_alpha  max_depth  min_samples_leaf  min_samples_split  count
0        0.0        4.0                 1                  2      2
1        0.0        5.0                 1                  2      1

In [11]:
outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = Ridge(random_state=42)

    param_grid = {
        "alpha": [0.001, 0.01, 0.1, 1, 10, 100],
        "fit_intercept": [True, False]
    }

    grid = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )

    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(grid.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== Ridge with nested LOOCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_dtr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_dtr)

# Best hyperparameters chosen in each outer fold
best_params_dtr = pd.DataFrame(best_params_per_fold)
display(best_params_dtr)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_dtr.value_counts().reset_index(name="count"))

=== Ridge with nested LOOCV ===
MAE  : 1.004226
RMSE : 1.698293
R²   : 0.996162

    y_true     y_pred  residual  abs_error
0   100.00  97.660557  2.339443   2.339443
1   100.00  97.461627  2.538373   2.538373
2   100.00  94.420973  5.579027   5.579027
3    50.00  53.829268 -3.829268   3.829268
4    50.00  54.532687 -4.532687   4.532687
5    50.00  55.035032 -5.035032   5.035032
6    25.00  24.932212  0.067788   0.067788
7    25.00  24.786270  0.213730   0.213730
8    25.00  24.866714  0.133286   0.133286
9    15.00  14.002918  0.997082   0.997082
10   15.00  13.944409  1.055591   1.055591
11   15.00  13.468744  1.531256   1.531256
12   10.00   9.130676  0.869324   0.869324
13   10.00   9.521409  0.478591   0.478591
14   10.00   9.345626  0.654374   0.654374
15    7.50   6.761973  0.738027   0.738027
16    7.50   7.124512  0.375488   0.375488
17    7.50   6.209297  1.290703   1.290703
18    5.00   4.510010  0.489990   0.489990
19    5.00   4.218189  0.781811   0.781811
20    5.00   4.191993  0.808007   0.808007
21    2.50   2.312313  0.187687   0.187687
22    2.50   2.197065  0.302935   0.302935
23    1.00   1.140977 -0.140977   0.140977
24    1.00   1.131931 -0.131931   0.131931
25    1.00   1.128731 -0.128731   0.128731
26    0.50   0.802491 -0.302491   0.302491
27    0.50   0.815190 -0.315190   0.315190
28    0.50   0.797022 -0.297022   0.297022
29    0.50   0.770510 -0.270510   0.270510
30    0.50   0.763933 -0.263933   0.263933
31    0.50   0.775898 -0.275898   0.275898
32    0.25   0.624024 -0.374024   0.374024
33    0.25   0.603984 -0.353984   0.353984
34    0.25   0.627294 -0.377294   0.377294
35    0.10   0.523265 -0.423265   0.423265
36    0.10   0.498263 -0.398263   0.398263
37    0.10   0.519035 -0.419035   0.419035
38    0.10   0.521082 -0.421082   0.421082
39    0.10   0.545919 -0.445919   0.445919

    alpha  fit_intercept
0   0.100          False
1   0.100          False
2   0.100          False
3   0.100          False
4   0.001           True
5   0.100          False
6   0.100          False
7   0.100          False
8   0.100          False
9   0.100          False
10  0.100          False
11  0.100          False
12  0.100          False
13  0.100          False
14  0.100          False
15  0.100          False
16  0.100          False
17  0.100          False
18  0.100          False
19  0.100          False
20  0.100          False
21  0.100          False
22  0.100          False
23  0.100          False
24  0.100          False
25  0.100          False
26  0.100          False
27  0.100          False
28  0.100          False
29  0.100          False
30  0.100          False
31  0.100          False
32  0.100          False
33  0.100          False
34  0.100          False
35  0.100          False
36  0.100          False
37  0.100          False
38  0.100          False
39  0.100          False

Most frequent best parameter sets:

   alpha  fit_intercept  count
0  0.100          False     39
1  0.001           True      1

In [12]:
outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = ElasticNet(random_state=42, max_iter=20000)

    param_grid = {
        "alpha": [1e-4, 1e-3, 1e-2, 1e-1, 1, 10],
        "l1_ratio": [0.1, 0.3, 0.5, 0.7, 0.9],
        "fit_intercept": [True, False]
    }

    grid = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )

    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(grid.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== Ridge with nested LOOCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_dtr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_dtr)

# Best hyperparameters chosen in each outer fold
best_params_dtr = pd.DataFrame(best_params_per_fold)
display(best_params_dtr)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_dtr.value_counts().reset_index(name="count"))

=== Ridge with nested LOOCV ===
MAE  : 0.949602
RMSE : 1.645826
R²   : 0.996395

    y_true     y_pred  residual  abs_error
0   100.00  97.211014  2.788986   2.788986
1   100.00  96.805793  3.194207   3.194207
2   100.00  93.986330  6.013670   6.013670
3    50.00  52.852102 -2.852102   2.852102
4    50.00  54.497418 -4.497418   4.497418
5    50.00  53.907864 -3.907864   3.907864
6    25.00  25.232553 -0.232553   0.232553
7    25.00  25.097926 -0.097926   0.097926
8    25.00  25.182973 -0.182973   0.182973
9    15.00  14.106086  0.893914   0.893914
10   15.00  14.047354  0.952646   0.952646
11   15.00  13.574545  1.425455   1.425455
12   10.00   9.167357  0.832643   0.832643
13   10.00   9.555621  0.444379   0.444379
14   10.00   9.371173  0.628827   0.628827
15    7.50   6.732303  0.767697   0.767697
16    7.50   7.100231  0.399769   0.399769
17    7.50   6.177900  1.322100   1.322100
18    5.00   4.454977  0.545023   0.545023
19    5.00   4.159215  0.840785   0.840785
20    5.00   4.126805  0.873195   0.873195
21    2.50   2.218327  0.281673   0.281673
22    2.50   2.107067  0.392933   0.392933
23    1.00   1.033881 -0.033881   0.033881
24    1.00   1.023357 -0.023357   0.023357
25    1.00   1.020645 -0.020645   0.020645
26    0.50   0.700229 -0.200229   0.200229
27    0.50   0.713070 -0.213070   0.213070
28    0.50   0.689827 -0.189827   0.189827
29    0.50   0.668411 -0.168411   0.168411
30    0.50   0.662554 -0.162554   0.162554
31    0.50   0.674242 -0.174242   0.174242
32    0.25   0.525755 -0.275755   0.275755
33    0.25   0.506476 -0.256476   0.256476
34    0.25   0.530150 -0.280150   0.280150
35    0.10   0.424291 -0.324291   0.324291
36    0.10   0.412539 -0.312539   0.312539
37    0.10   0.415298 -0.315298   0.315298
38    0.10   0.426065 -0.326065   0.326065
39    0.10   0.438541 -0.338541   0.338541

     alpha  fit_intercept  l1_ratio
0   0.0100          False       0.7
1   0.0100          False       0.7
2   0.0100          False       0.7
3   0.0100          False       0.9
4   0.0001           True       0.9
5   0.0100          False       0.9
6   0.0100          False       0.7
7   0.0100          False       0.7
8   0.0100          False       0.7
9   0.0100          False       0.7
10  0.0100          False       0.7
11  0.0100          False       0.7
12  0.0100          False       0.7
13  0.0100          False       0.7
14  0.0100          False       0.7
15  0.0100          False       0.7
16  0.0100          False       0.7
17  0.0100          False       0.7
18  0.0100          False       0.7
19  0.0100          False       0.7
20  0.0100          False       0.7
21  0.0100          False       0.7
22  0.0100          False       0.7
23  0.0100          False       0.7
24  0.0100          False       0.7
25  0.0100          False       0.7
26  0.0100          False       0.7
27  0.0100          False       0.7
28  0.0100          False       0.7
29  0.0100          False       0.7
30  0.0100          False       0.7
31  0.0100          False       0.7
32  0.0100          False       0.7
33  0.0100          False       0.7
34  0.0100          False       0.7
35  0.0100          False       0.7
36  0.0100          False       0.7
37  0.0100          False       0.7
38  0.0100          False       0.7
39  0.0100          False       0.7

Most frequent best parameter sets:

    alpha  fit_intercept  l1_ratio  count
0  0.0100          False       0.7     37
1  0.0100          False       0.9      2
2  0.0001           True       0.9      1

In [13]:
outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = SVR()

    param_grid = {
        "kernel": ["rbf", "linear"],
        "C": [0.1, 1, 10, 100],
        "epsilon": [0.01, 0.05, 0.1, 0.5, 1.0],
        "gamma": ["scale", "auto"]
    }

    grid = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1
    )

    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(grid.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== Ridge with nested LOOCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_dtr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_dtr)

# Best hyperparameters chosen in each outer fold
best_params_dtr = pd.DataFrame(best_params_per_fold)
display(best_params_dtr)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_dtr.value_counts().reset_index(name="count"))

=== Ridge with nested LOOCV ===
MAE  : 2.342918
RMSE : 6.415718
R²   : 0.945221

    y_true     y_pred   residual  abs_error
0   100.00  78.354696  21.645304  21.645304
1   100.00  76.719992  23.280008  23.280008
2   100.00  76.330393  23.669607  23.669607
3    50.00  52.579888  -2.579888   2.579888
4    50.00  56.298720  -6.298720   6.298720
5    50.00  54.615780  -4.615780   4.615780
6    25.00  25.117623  -0.117623   0.117623
7    25.00  24.955873   0.044127   0.044127
8    25.00  25.028432  -0.028432   0.028432
9    15.00  14.135255   0.864745   0.864745
10   15.00  14.074264   0.925736   0.925736
11   15.00  13.624124   1.375876   1.375876
12   10.00   9.226561   0.773439   0.773439
13   10.00   9.644016   0.355984   0.355984
14   10.00   9.444449   0.555551   0.555551
15    7.50   6.948788   0.551212   0.551212
16    7.50   7.244776   0.255224   0.255224
17    7.50   6.354937   1.145063   1.145063
18    5.00   4.617414   0.382586   0.382586
19    5.00   4.378558   0.621442   0.621442
20    5.00   4.355486   0.644514   0.644514
21    2.50   2.441457   0.058543   0.058543
22    2.50   2.320578   0.179422   0.179422
23    1.00   1.240430  -0.240430   0.240430
24    1.00   1.302864  -0.302864   0.302864
25    1.00   1.299609  -0.299609   0.299609
26    0.50   0.890116  -0.390116   0.390116
27    0.50   0.979115  -0.479115   0.479115
28    0.50   0.892104  -0.392104   0.392104
29    0.50   0.517037  -0.017037   0.017037
30    0.50   0.509000  -0.009000   0.009000
31    0.50   0.522085  -0.022085   0.022085
32    0.25   0.306178  -0.056178   0.056178
33    0.25   0.222526   0.027474   0.027474
34    0.25   0.251136  -0.001136   0.001136
35    0.10   0.146552  -0.046552   0.046552
36    0.10   0.139146  -0.039146   0.039146
37    0.10   0.074003   0.025997   0.025997
38    0.10   0.201675  -0.101675   0.101675
39    0.10   0.397354  -0.297354   0.297354

        C  epsilon  gamma  kernel
0     0.1     0.50  scale  linear
1     0.1     0.50  scale  linear
2     0.1     0.50  scale  linear
3   100.0     1.00  scale  linear
4   100.0     0.01  scale  linear
5   100.0     0.01  scale  linear
6   100.0     0.05  scale  linear
7   100.0     0.05  scale  linear
8   100.0     0.05  scale  linear
9   100.0     0.05  scale  linear
10  100.0     0.05  scale  linear
11  100.0     0.10  scale  linear
12  100.0     0.10  scale  linear
13  100.0     0.10  scale  linear
14  100.0     0.10  scale  linear
15  100.0     0.01  scale  linear
16  100.0     0.01  scale  linear
17  100.0     0.01  scale  linear
18  100.0     0.01  scale  linear
19  100.0     0.01  scale  linear
20  100.0     0.01  scale  linear
21  100.0     0.01  scale  linear
22  100.0     0.01  scale  linear
23  100.0     0.01  scale  linear
24  100.0     0.01  scale  linear
25  100.0     0.01  scale  linear
26  100.0     0.01  scale  linear
27  100.0     0.01  scale  linear
28  100.0     0.01  scale  linear
29  100.0     0.01  scale  linear
30  100.0     0.01  scale  linear
31  100.0     0.01  scale  linear
32  100.0     0.01  scale  linear
33  100.0     0.01  scale  linear
34  100.0     0.01  scale  linear
35  100.0     0.01  scale  linear
36  100.0     0.01  scale  linear
37  100.0     0.01  scale  linear
38  100.0     0.01  scale  linear
39  100.0     0.01  scale  linear

Most frequent best parameter sets:

       C  epsilon  gamma  kernel  count
0  100.0     0.01  scale  linear     27
1  100.0     0.05  scale  linear      5
2  100.0     0.10  scale  linear      4
3    0.1     0.50  scale  linear      3
4  100.0     1.00  scale  linear      1

In [15]:
import numpy as np
import pandas as pd

from sklearn.model_selection import LeaveOneOut, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from skopt import BayesSearchCV
from skopt.space import Integer, Categorical

outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = RandomForestRegressor(random_state=42, n_jobs=-1)

    search_spaces = {
        "n_estimators": Integer(100, 500),
        "max_depth": Integer(2, 10),
        "min_samples_split": Integer(2, 8),
        "min_samples_leaf": Integer(1, 4),
        "max_features": Categorical([1.0, "sqrt", 0.75])
    }

    opt = BayesSearchCV(
        estimator=model,
        search_spaces=search_spaces,
        n_iter=25,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1,
        random_state=42,
        refit=True
    )

    opt.fit(X_train, y_train)
    best_model = opt.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(opt.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== RandomForestRegressor with nested LOOCV + BayesSearchCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_rfr = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_rfr)

# Best hyperparameters chosen in each outer fold
best_params_rfr = pd.DataFrame(best_params_per_fold)
display(best_params_rfr)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_rfr.value_counts().reset_index(name="count"))

/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(2), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(2), 0.75, np.int64(3), np.int64(2), np.int64(386)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(2), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 1.0, np.int64(1), np.int64(6), np.int64(458)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(2), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(3), np.int64(5), np.int64(316)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(2), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(3), np.int64(5), np.int64(370)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(3), 'sqrt', np.int64(2), np.int64(6), np.int64(305)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(3), np.int64(2), np.int64(438)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(1), np.int64(5), np.int64(263)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(10), 'sqrt', np.int64(1), np.int64(4), np.int64(184)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(3), np.int64(7), np.int64(195)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(9), 1.0, np.int64(1), np.int64(5), np.int64(158)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(3), np.int64(7), np.int64(195)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 'sqrt', np.int64(1), np.int64(8), np.int64(288)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(1), np.int64(2), np.int64(165)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(396)] before, using random point [np.int64(6), 'sqrt', np.int64(2), np.int64(6), np.int64(467)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(396)] before, using random point [np.int64(6), 'sqrt', np.int64(2), np.int64(6), np.int64(467)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(9), 'sqrt', np.int64(3), np.int64(8), np.int64(404)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 'sqrt', np.int64(1), np.int64(8), np.int64(288)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(10), 1.0, np.int64(1), np.int64(7), np.int64(286)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 'sqrt', np.int64(4), np.int64(7), np.int64(110)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 1.0, np.int64(2), np.int64(5), np.int64(306)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(1), np.int64(2), np.int64(165)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(10), 1.0, np.int64(1), np.int64(7), np.int64(286)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 'sqrt', np.int64(4), np.int64(7), np.int64(110)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 1.0, np.int64(2), np.int64(5), np.int64(306)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(1), np.int64(2), np.int64(165)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(2), np.int64(8), np.int64(429)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(9), 'sqrt', np.int64(3), np.int64(2), np.int64(475)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(6), 1.0, np.int64(3), np.int64(8), np.int64(353)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(10), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 0.75, np.int64(3), np.int64(3), np.int64(323)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 0.75, np.int64(3), np.int64(3), np.int64(323)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(4), np.int64(4), np.int64(405)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(2), np.int64(3), np.int64(302)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(2), np.int64(3), np.int64(330)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(4), np.int64(4), np.int64(405)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(2), np.int64(3), np.int64(302)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(2), np.int64(3), np.int64(330)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 'sqrt', np.int64(4), np.int64(7), np.int64(110)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(2), 0.75, np.int64(2), np.int64(4), np.int64(337)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(3), np.int64(5), np.int64(276)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(0.75), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(1), np.int64(5), np.int64(187)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(6), 'sqrt', np.int64(2), np.int64(6), np.int64(467)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(9), 1.0, np.int64(1), np.int64(5), np.int64(158)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(9), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 'sqrt', np.int64(1), np.int64(7), np.int64(492)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(7), 1.0, np.int64(4), np.int64(4), np.int64(405)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(4), 1.0, np.int64(2), np.int64(3), np.int64(302)]
  warnings.warn(
/Users/andrei/Work/PhD/pyocyanin-ai/.venv/lib/python3.12/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(8), np.float64(1.0), np.int64(1), np.int64(2), np.int64(500)] before, using random point [np.int64(8), 0.75, np.int64(2), np.int64(3), np.int64(330)]
  warnings.warn(

=== RandomForestRegressor with nested LOOCV + BayesSearchCV ===
MAE  : 0.982894
RMSE : 2.213000
R²   : 0.993482

    y_true     y_pred  residual  abs_error
0   100.00  94.969512  5.030488   5.030488
1   100.00  91.311475  8.688525   8.688525
2   100.00  91.337386  8.662614   8.662614
3    50.00  47.866324  2.133676   2.133676
4    50.00  52.460000 -2.460000   2.460000
5    50.00  49.290000  0.710000   0.710000
6    25.00  23.824885  1.175115   1.175115
7    25.00  23.824885  1.175115   1.175115
8    25.00  23.824885  1.175115   1.175115
9    15.00  14.319809  0.680191   0.680191
10   15.00  15.998920 -0.998920   0.998920
11   15.00  14.322660  0.677340   0.677340
12   10.00   9.849624  0.150376   0.150376
13   10.00   8.935000  1.065000   1.065000
14   10.00  10.000000  0.000000   0.000000
15    7.50   7.021684  0.478316   0.478316
16    7.50   7.850000 -0.350000   0.350000
17    7.50   7.232143  0.267857   0.267857
18    5.00   5.490431 -0.490431   0.490431
19    5.00   4.835443  0.164557   0.164557
20    5.00   4.746835  0.253165   0.253165
21    2.50   1.995215  0.504785   0.504785
22    2.50   1.859000  0.641000   0.641000
23    1.00   1.024616 -0.024616   0.024616
24    1.00   1.337000 -0.337000   0.337000
25    1.00   1.337000 -0.337000   0.337000
26    0.50   0.516582 -0.016582   0.016582
27    0.50   0.588500 -0.088500   0.088500
28    0.50   0.522500 -0.022500   0.022500
29    0.50   0.491000  0.009000   0.009000
30    0.50   0.491000  0.009000   0.009000
31    0.50   0.491000  0.009000   0.009000
32    0.25   0.244530  0.005470   0.005470
33    0.25   0.228600  0.021400   0.021400
34    0.25   0.243213  0.006787   0.006787
35    0.10   0.255491 -0.155491   0.155491
36    0.10   0.110382 -0.010382   0.010382
37    0.10   0.256866 -0.156866   0.156866
38    0.10   0.120000 -0.020000   0.020000
39    0.10   0.253600 -0.153600   0.153600

    max_depth  max_features  min_samples_leaf  min_samples_split  n_estimators
0          10          0.75                 1                  2           328
1          10          0.75                 1                  2           305
2          10          0.75                 1                  2           329
3          10          0.75                 1                  2           389
4           7          0.75                 1                  2           500
5          10          0.75                 1                  2           500
6          10          0.75                 1                  2           434
7          10          0.75                 1                  2           434
8          10          0.75                 1                  2           434
9          10          0.75                 1                  2           419
10         10          0.75                 1                  2           463
11         10          0.75                 1                  2           406
12          9          0.75                 1                  2           399
13          9          0.75                 1                  2           500
14          9          0.75                 1                  2           500
15         10          0.75                 1                  2           392
16         10          0.75                 1                  2           500
17          9          0.75                 1                  2           392
18         10          0.75                 1                  2           418
19         10          0.75                 1                  2           395
20         10          0.75                 1                  2           395
21         10          0.75                 1                  2           418
22         10          1.00                 1                  2           500
23          5          1.00                 1                  2           422
24          9          1.00                 1                  2           500
25          9          1.00                 1                  2           500
26         10          0.75                 1                  2           392
27          8          0.75                 1                  2           500
28          9          0.75                 1                  2           500
29          9          0.75                 1                  2           500
30          8          1.00                 1                  2           500
31          8          1.00                 1                  2           500
32          5          0.75                 1                  2           500
33          9          0.75                 1                  2           500
34         10          0.75                 1                  2           442
35          5          1.00                 1                  2           500
36         10          1.00                 1                  2           419
37          5          1.00                 1                  2           500
38          9          1.00                 1                  2           500
39          8          1.00                 1                  2           500

Most frequent best parameter sets:

    max_depth  max_features  ...  n_estimators  count
0           9          0.75  ...           500      5
1          10          0.75  ...           434      3
2           9          1.00  ...           500      3
3           8          1.00  ...           500      3
4          10          0.75  ...           500      2
5          10          0.75  ...           392      2
6          10          0.75  ...           418      2
7          10          0.75  ...           395      2
8           5          1.00  ...           500      2
9          10          0.75  ...           328      1
10         10          0.75  ...           305      1
11         10          0.75  ...           329      1
12         10          0.75  ...           389      1
13          7          0.75  ...           500      1
14         10          0.75  ...           419      1
15         10          0.75  ...           463      1
16         10          0.75  ...           406      1
17          9          0.75  ...           399      1
18          9          0.75  ...           392      1
19         10          1.00  ...           500      1
20          5          1.00  ...           422      1
21          8          0.75  ...           500      1
22          5          0.75  ...           500      1
23         10          0.75  ...           442      1
24         10          1.00  ...           419      1

[25 rows x 6 columns]

In [16]:
from skopt import BayesSearchCV
from skopt.space import Integer, Real

outer_cv = LeaveOneOut()

y_true = []
y_pred = []
best_params_per_fold = []

for train_idx, test_idx in outer_cv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # Inner CV for hyperparameter tuning
    inner_cv = KFold(n_splits=3, shuffle=True, random_state=42)

    model = XGBRegressor(
        objective="reg:squarederror",
        random_state=42,
        n_jobs=1,
        verbosity=0
    )

    search_spaces = {
        "n_estimators": Integer(50, 500),
        "max_depth": Integer(2, 8),
        "learning_rate": Real(0.01, 0.3, prior="log-uniform"),
        "subsample": Real(0.6, 1.0),
        "colsample_bytree": Real(0.6, 1.0),
        "min_child_weight": Integer(1, 10),
        "gamma": Real(1e-8, 5.0, prior="log-uniform"),
        "reg_alpha": Real(1e-8, 10.0, prior="log-uniform"),
        "reg_lambda": Real(1e-3, 10.0, prior="log-uniform")
    }

    opt = BayesSearchCV(
        estimator=model,
        search_spaces=search_spaces,
        n_iter=25,
        cv=inner_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=-1,
        random_state=42,
        refit=True
    )

    opt.fit(X_train, y_train)
    best_model = opt.best_estimator_

    pred = best_model.predict(X_test)[0]

    y_true.append(y_test.iloc[0])
    y_pred.append(pred)
    best_params_per_fold.append(opt.best_params_)

# Convert to arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Metrics
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print("=== XGBRegressor with nested LOOCV + BayesSearchCV ===")
print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R²   : {r2:.6f}")

# Per-sample prediction table
results_xgb = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "residual": y_true - y_pred,
    "abs_error": np.abs(y_true - y_pred)
})

display(results_xgb)

# Best hyperparameters chosen in each outer fold
best_params_xgb = pd.DataFrame(best_params_per_fold)
display(best_params_xgb)

# Optional: most frequent best parameter combination
print("\nMost frequent best parameter sets:")
display(best_params_xgb.value_counts().reset_index(name="count"))

=== XGBRegressor with nested LOOCV + BayesSearchCV ===
MAE  : 2.599263
RMSE : 6.507462
R²   : 0.943644

    y_true     y_pred   residual  abs_error
0   100.00  99.999191   0.000809   0.000809
1   100.00  79.253517  20.746483  20.746483
2   100.00  79.253517  20.746483  20.746483
3    50.00  24.285742  25.714258  25.714258
4    50.00  58.069530  -8.069530   8.069530
5    50.00  44.644360   5.355640   5.355640
6    25.00  19.371653   5.628347   5.628347
7    25.00  24.308384   0.691616   0.691616
8    25.00  24.899021   0.100979   0.100979
9    15.00  15.169655  -0.169655   0.169655
10   15.00  14.999915   0.000085   0.000085
11   15.00   9.996648   5.003352   5.003352
12   10.00   7.500788   2.499212   2.499212
13   10.00  10.015379  -0.015379   0.015379
14   10.00  10.087172  -0.087172   0.087172
15    7.50   7.467467   0.032533   0.032533
16    7.50   7.027553   0.472447   0.472447
17    7.50   5.000981   2.499019   2.499019
18    5.00   5.117813  -0.117813   0.117813
19    5.00   4.839080   0.160920   0.160920
20    5.00   2.623842   2.376158   2.376158
21    2.50   2.395728   0.104272   0.104272
22    2.50   1.204759   1.295241   1.295241
23    1.00   1.199005  -0.199005   0.199005
24    1.00   0.612132   0.387868   0.387868
25    1.00   0.853249   0.146751   0.146751
26    0.50   0.500053  -0.000053   0.000053
27    0.50   1.069259  -0.569259   0.569259
28    0.50   0.250388   0.249612   0.249612
29    0.50   0.359688   0.140312   0.140312
30    0.50   0.500899  -0.000899   0.000899
31    0.50   0.479341   0.020659   0.020659
32    0.25   0.258029  -0.008029   0.008029
33    0.25   0.531793  -0.281793   0.281793
34    0.25   0.235184   0.014816   0.014816
35    0.10   0.105954  -0.005954   0.005954
36    0.10   0.098103   0.001897   0.001897
37    0.10   0.102438  -0.002438   0.002438
38    0.10   0.083827   0.016173   0.016173
39    0.10   0.137584  -0.037584   0.037584

    colsample_bytree         gamma  ...  reg_lambda  subsample
0           0.600000  1.954576e-07  ...    1.910806   1.000000
1           0.939518  3.391347e-01  ...    0.100103   0.768286
2           0.939518  3.391347e-01  ...    0.100103   0.768286
3           0.600000  1.000000e-08  ...    0.168799   0.901875
4           0.600000  5.000000e+00  ...    0.028119   0.600000
5           0.600000  1.000000e-08  ...    0.001000   0.643701
6           0.691977  7.497092e-01  ...    0.213743   0.745019
7           1.000000  2.289701e+00  ...    0.001000   0.782984
8           1.000000  2.289701e+00  ...    0.001000   0.782984
9           0.834024  7.989800e-04  ...    0.035269   0.936406
10          1.000000  1.592530e-07  ...   10.000000   1.000000
11          1.000000  1.000000e-08  ...    0.001000   1.000000
12          1.000000  1.000000e-08  ...    0.001540   1.000000
13          0.942770  1.000000e-08  ...    0.004606   0.907707
14          0.980934  1.394054e-02  ...    0.004097   0.684698
15          1.000000  1.312479e-03  ...    0.023754   0.826237
16          0.863345  1.000000e-08  ...    0.013845   0.600000
17          1.000000  1.000000e-08  ...    0.001171   0.816320
18          0.967368  1.408065e-02  ...    0.001000   0.659452
19          1.000000  3.022664e-01  ...    0.001000   0.836936
20          1.000000  3.022664e-01  ...    0.001000   0.836936
21          1.000000  1.521026e-02  ...    5.917124   0.843137
22          1.000000  3.623237e-01  ...    0.001000   0.600000
23          0.600000  1.000000e-08  ...   10.000000   1.000000
24          1.000000  1.000000e-08  ...   10.000000   0.600000
25          1.000000  1.000000e-08  ...   10.000000   0.600000
26          0.999907  1.000000e-08  ...    0.001000   1.000000
27          0.718300  5.000000e+00  ...    0.001000   0.671513
28          0.842248  4.743506e-05  ...    0.001000   0.972532
29          0.600000  1.000000e-08  ...   10.000000   0.962005
30          1.000000  1.389246e-08  ...    0.001630   0.600000
31          1.000000  1.842380e-08  ...   10.000000   0.796169
32          0.600000  1.000000e-08  ...    0.001000   1.000000
33          1.000000  1.366389e+00  ...    0.001000   0.985886
34          1.000000  1.264545e-01  ...    0.032780   0.683441
35          0.812909  1.000000e-08  ...    0.001000   0.976526
36          0.850225  1.000000e-08  ...    0.001000   0.977348
37          0.909103  5.526765e-05  ...    0.063818   0.978370
38          1.000000  1.899607e-03  ...    0.001986   0.823423
39          1.000000  8.735297e-07  ...   10.000000   0.755666

[40 rows x 9 columns]

Most frequent best parameter sets:

    colsample_bytree         gamma  learning_rate  ...  reg_lambda  subsample  count
0           0.939518  3.391347e-01       0.069808  ...    0.100103   0.768286      2
1           1.000000  2.289701e+00       0.299971  ...    0.001000   0.782984      2
2           1.000000  3.022664e-01       0.025408  ...    0.001000   0.836936      2
3           1.000000  1.000000e-08       0.300000  ...   10.000000   0.600000      2
4           0.600000  1.954576e-07       0.300000  ...    1.910806   1.000000      1
5           0.600000  1.000000e-08       0.300000  ...    0.168799   0.901875      1
6           0.600000  5.000000e+00       0.300000  ...    0.028119   0.600000      1
7           0.600000  1.000000e-08       0.010000  ...    0.001000   0.643701      1
8           0.691977  7.497092e-01       0.063061  ...    0.213743   0.745019      1
9           0.834024  7.989800e-04       0.038268  ...    0.035269   0.936406      1
10          1.000000  1.592530e-07       0.096446  ...   10.000000   1.000000      1
11          1.000000  1.000000e-08       0.016588  ...    0.001000   1.000000      1
12          1.000000  1.000000e-08       0.300000  ...    0.001540   1.000000      1
13          0.942770  1.000000e-08       0.056824  ...    0.004606   0.907707      1
14          0.980934  1.394054e-02       0.300000  ...    0.004097   0.684698      1
15          1.000000  1.312479e-03       0.027783  ...    0.023754   0.826237      1
16          0.863345  1.000000e-08       0.300000  ...    0.013845   0.600000      1
17          1.000000  1.000000e-08       0.087287  ...    0.001171   0.816320      1
18          0.967368  1.408065e-02       0.018976  ...    0.001000   0.659452      1
19          1.000000  1.521026e-02       0.300000  ...    5.917124   0.843137      1
20          1.000000  3.623237e-01       0.300000  ...    0.001000   0.600000      1
21          0.600000  1.000000e-08       0.300000  ...   10.000000   1.000000      1
22          0.999907  1.000000e-08       0.219796  ...    0.001000   1.000000      1
23          0.718300  5.000000e+00       0.109116  ...    0.001000   0.671513      1
24          0.842248  4.743506e-05       0.270410  ...    0.001000   0.972532      1
25          0.600000  1.000000e-08       0.300000  ...   10.000000   0.962005      1
26          1.000000  1.389246e-08       0.104828  ...    0.001630   0.600000      1
27          1.000000  1.842380e-08       0.300000  ...   10.000000   0.796169      1
28          0.600000  1.000000e-08       0.010000  ...    0.001000   1.000000      1
29          1.000000  1.366389e+00       0.300000  ...    0.001000   0.985886      1
30          1.000000  1.264545e-01       0.190504  ...    0.032780   0.683441      1
31          0.812909  1.000000e-08       0.099554  ...    0.001000   0.976526      1
32          0.850225  1.000000e-08       0.151365  ...    0.001000   0.977348      1
33          0.909103  5.526765e-05       0.201452  ...    0.063818   0.978370      1
34          1.000000  1.899607e-03       0.300000  ...    0.001986   0.823423      1
35          1.000000  8.735297e-07       0.300000  ...   10.000000   0.755666      1

[36 rows x 10 columns]